server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}

  security:
    secret-key: ${SECRET_KEY:asdfasfdasfadsf}
    access-exp: ${ACCESS_EXP:180}
    refresh-exp: ${REFRESH_EXP:180}

open-api:
  league-of-legend: ${LOL_APIKEY}
  battle-ground: ${PUBG_APIKEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME:gatihaeyo}
    ses:
      source: ${SES_SENDER}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error